name: crop_image
description: An image cropper widget, with 90-degree rotations. Supports mobile, web and desktop.
version: 1.0.13
homepage: https://github.com/deakjahn/crop_image

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
